pub mod aabb_tree;
pub mod abstract_graph;
pub mod ambient_occlusion;
pub mod angle_defect;
pub mod arap_deform;
pub mod area_equalize;
pub mod area_weighted_normals;
pub mod array_calculator;
pub mod array_statistics;
pub mod array_transform;
pub mod aspect_ratio;
pub mod aspect_ratio_compute;
pub mod aspect_ratio_filter;
pub mod aspect_ratio_improve;
pub mod aspect_ratio_stats;
pub mod axis_aligned_slice;
pub mod axis_projection;
pub mod barycentric_subdivide;
pub mod bbox_ops;
pub mod bend;
pub mod bilateral_smooth;
pub mod boolean_cells;
pub mod boolean_difference;
pub mod boolean_exact;
pub mod boolean_point_set;
pub mod boolean_robust;
pub mod boolean_split;
pub mod boolean_union_approx;
pub mod border_distance;
pub mod boundary_analysis;
pub mod boundary_edges;
pub mod boundary_fill;
pub mod boundary_loop;
pub mod bounding_box_mesh;
pub mod cage_deform;
pub mod cage_transform;
pub mod cell_connectivity_matrix;
pub mod cell_subdivision;
pub mod cell_to_point_data;
pub mod cell_to_point_interpolate;
pub mod cell_to_vertex;
pub mod center;
pub mod centroid;
pub mod centroid_ops;
pub mod circumradius;
pub mod circumscribed_sphere;
pub mod clip_by_plane;
pub mod closest_pair;
pub mod closest_point;
pub mod closest_point_on_surface;
pub mod coarsen;
pub mod collapse_degenerate;
pub mod collapse_short_edges;
pub mod color_by_data;
pub mod comparison;
pub mod compute_edge_lengths;
pub mod compute_face_areas;
pub mod compute_volume;
pub mod conformal_factor;
pub mod connected_components_count;
pub mod connected_face_groups;
pub mod connectivity_ops;
pub mod contour_lines;
pub mod contour_on_mesh;
pub mod convex_check;
pub mod convex_decompose;
pub mod convex_decomposition;
pub mod convex_hull;
pub mod convex_hull_2d;
pub mod convex_hull_3d;
pub mod convex_layers;
pub mod convexity_analysis;
pub mod coplanar_detection;
pub mod coplanar_merge;
pub mod correspondence;
pub mod cross_section;
pub mod curvature_color;
pub mod curvature_color_map;
pub mod curvature_flow_smooth;
pub mod curvature_histogram;
pub mod curvature_line;
pub mod curvature_map_to_color;
pub mod curvature_mean_simple;
pub mod curvature_simple;
pub mod curvature_tensor;
pub mod curvature_tensor_analysis;
pub mod curvature_visualization;
pub mod cylinder_clip;
pub mod data_transfer;
pub mod decimate_angle;
pub mod decimate_pro;
pub mod decimate_progressive;
pub mod decimate_quadric_error;
pub mod decimate_vertex_clustering;
pub mod deformation_energy;
pub mod delaunay_triangulate_2d;
pub mod depth_sort;
pub mod diff;
pub mod dihedral_angle_array;
pub mod dihedral_angles;
pub mod displacement_analysis;
pub mod distance_between;
pub mod distance_between_meshes;
pub mod distance_field;
pub mod distance_map;
pub mod dual_contour;
pub mod dual_graph;
pub mod dual_graph_analysis;
pub mod duplicate_faces;
pub mod edge_analysis;
pub mod edge_angle_stats;
pub mod edge_collapse_quality;
pub mod edge_color;
pub mod edge_flip;
pub mod edge_graph;
pub mod edge_length_equalize;
pub mod edge_length_stats;
pub mod edge_midpoint_split;
pub mod edge_network;
pub mod edge_split;
pub mod edge_swap;
pub mod edge_valence_stats;
pub mod elastic_deform;
pub mod explode;
pub mod export_stats;
pub mod extract_boundary;
pub mod extract_boundary_loop;
pub mod extract_cells_by_type;
pub mod extract_largest_component;
pub mod extract_sharp_features;
pub mod extrude_along_normal;
pub mod extrude_profile;
pub mod face_area_distribution;
pub mod face_area_filter;
pub mod face_area_stats;
pub mod face_centroid_array;
pub mod face_centroid_filter;
pub mod face_cluster;
pub mod face_color;
pub mod face_data_stats;
pub mod face_group_by_normal;
pub mod face_group_ops;
pub mod face_normal_angle;
pub mod face_normal_array;
pub mod face_normal_consistency;
pub mod face_orientation;
pub mod face_pair_angle;
pub mod face_quality_metrics;
pub mod face_skewness;
pub mod face_strip_builder;
pub mod feature_angle_detect;
pub mod feature_extraction;
pub mod feature_line;
pub mod feature_size;
pub mod field_interpolation;
pub mod flatten;
pub mod flip_normals;
pub mod frame_field;
pub mod geodesic_distance_dijkstra;
pub mod geodesic_distance_heat;
pub mod geodesic_farthest_point;
pub mod geodesic_heat;
pub mod geodesic_heat_kernel;
pub mod geodesic_partition;
pub mod geodesic_path;
pub mod geodesic_voronoi;
pub mod graph_algorithms;
pub mod half_edge;
pub mod harmonic_map;
pub mod hausdorff_directed;
pub mod heat_equation;
pub mod heat_geodesic_iso;
pub mod heat_kernel;
pub mod heat_method_distance;
pub mod hole_detect;
pub mod hole_filling;
pub mod inertia;
pub mod info;
pub mod inscribed_sphere;
pub mod intersection_query;
pub mod intrinsic_distance;
pub mod invert_faces;
pub mod iso_line;
pub mod label_propagation;
pub mod laplacian_deform_simple;
pub mod laplacian_eigenmaps;
pub mod laplacian_energy;
pub mod laplacian_matrix;
pub mod laplacian_smooth_simple;
pub mod laplacian_smooth_weighted;
pub mod laplacian_solve;
pub mod laplacian_spectrum;
pub mod level_set;
pub mod manifold_check;
pub mod marching_squares;
pub mod measure;
pub mod measure_advanced;
pub mod merge;
pub mod merge_ops;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_abstract_simplicial;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_adaptive_curvature;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_add_noise;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_align_to_axis;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_angle_defect;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_apply_transform_4x4;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_area_distortion;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_area_weighted_normals;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_array_combine;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_array_gradient;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_array_histogram;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_array_ops;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_array_statistics_compute;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_aspect_ratio;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_attach_curvature;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_attach_distance_to_centroid;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_attach_edge_count;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_attach_face_index;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_attach_face_normal_deviation;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_attach_normal_angle_to_axis;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_attach_spherical_coords;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_barycentric_coords;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_biharmonic_smooth;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_bilateral_smooth;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_boolean_inside_outside;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_boolean_simple;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_boolean_subtract;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_boolean_union_simple;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_boundary_count;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_boundary_locked_smooth;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_boundary_loops;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_bounding_box;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_center_scale;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_centroid_distance;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_centroid_distance_field;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_circumradius;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_clip_box;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_clip_cylinder;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_clip_sphere;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_close_small_holes;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_closest_point;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_coarsen_uniform;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_collapse_flat_tris;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_component_sizes;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_compute_area_per_vertex;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_compute_moment_of_inertia;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_compute_normals_simple;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_compute_signed_volume;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_conformal_factor;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_conformal_map_approx;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_connected_component_sizes;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_connected_components;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_contour_tree;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_convex_decompose;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_convex_hull_3d_simple;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_convexity;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_coplanar_group;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_copy;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_cotan_laplacian_solve;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_cotan_smooth;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_cotan_weights;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_cotangent_embedding;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_crop_half;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_curvature_color_simple;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_curvature_entropy;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_curvature_flow_willmore;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_curvature_laplacian_beltrami;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_curvature_line_extraction;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_curvature_scale_space;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_curvature_smooth;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_curvature_tensor;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_curvature_tensor_estimate;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_cvt_relaxation;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_cylindrical_uv;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_decimate_edge_length;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_decimate_random;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_decimate_vertex;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_deform_ffd;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_deform_lattice;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_delaunay_check;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_diffusion_distance;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_dihedral_angles;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_discrete_connection;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_discrete_curvature_tensor;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_discrete_exterior_calculus;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_discrete_flow_complex;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_discrete_gauss_map;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_discrete_hodge_star;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_discrete_laplacian_spectrum;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_discrete_mean_curvature_flow;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_discrete_morse_gradient;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_discrete_ricci_flow;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_displacement_field;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_distance_field_to_scalar;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_distance_histogram;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_distance_to_axis;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_distance_to_plane;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_distance_to_point;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_dual_contour_simple;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_dual_graph;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_dual_mesh;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_edge_angle_stats;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_edge_collapse;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_edge_collapse_adaptive;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_edge_collapse_preserving;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_edge_detect;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_edge_flip;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_edge_graph_build;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_edge_histogram;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_edge_midpoint_mesh;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_edge_ratio;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_edge_split;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_edge_to_tube;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_edge_weight_compute;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_elevation;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_extract_boundary_vertices;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_extract_faces_by_scalar;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_extract_interior_vertices;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_extract_largest_component;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_extract_manifold_edges;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_extract_plane_slice;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_extract_scalar_range;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_extract_silhouette;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_extract_vertices;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_extremal_graph;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_extrinsic_curvature;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_extrude;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_extrude_normals;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_face_angle_stats;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_face_area;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_face_area_weighted_normals;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_face_aspect_ratio;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_face_centroid;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_face_color_by_normal;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_face_connectivity_label;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_face_connectivity_matrix;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_face_count;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_face_label_propagate;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_face_normals;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_face_pair_ops;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_face_planarity;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_face_to_vertex;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_fast_marching;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_feature_edge_angle;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_feature_line;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_feature_line_field;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_feature_persistence_filter;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_feature_size_estimate;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_find_closest_vertex_to_points;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_flatten_to_plane;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_flip_normals;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_from_point_cloud;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_functional_map;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_gaussian_smooth;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_genus;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_geodesic_centroid;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_geodesic_contours;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_geodesic_convex_hull;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_geodesic_disk;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_geodesic_distance_dijkstra;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_geodesic_farthest_sampling;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_geodesic_field;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_geodesic_heat_signature;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_geodesic_medial_axis;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_geodesic_smooth;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_geodesic_voronoi;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_geodesic_voronoi_diagram;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_graph_laplacian_features;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_half_edge;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_harmonic_coords;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_harmonic_field;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_hausdorff_distance;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_heat_flow_steady;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_heat_geodesic;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_heat_kernel_distance;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_heat_kernel_signature;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_heat_method_geodesic;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_height_map;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_helmholtz_hodge;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_hodge_decomposition;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_hole_fill_simple;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_icp_align;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_inscribed_sphere;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_interpolate_between;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_intrinsic_delaunay;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_iso_surface_on_mesh;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_isolation_score;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_jacobian_quality;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_label_by_normal_cluster;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_laplacian_cotangent;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_laplacian_deform_interactive;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_laplacian_deform_multihandle;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_laplacian_eigenmaps;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_laplacian_eigenvalues;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_laplacian_heat_diffuse;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_laplacian_matrix;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_laplacian_matrix_build;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_laplacian_smooth_boundary_free;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_laplacian_spectral_basis;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_laplacian_vector;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_local_basis;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_marching_front;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_mean_edge_length;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_mean_value_coords;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_measure_angles;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_merge_close_components;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_merge_close_vertices;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_mesh_boolean_classify;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_mirror;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_mirror_plane;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_morse_complex_segmentation;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_noise_perturb;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_normal_cluster;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_normal_consistency;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_normal_deviation;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_normalize_bounds;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_offset_shell;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_offset_surface;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_one_ring_curvature;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_optimal_delaunay;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_optimal_transport_approx;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_optimal_transport_on_surface;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_orient;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_orient_normals;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_paint_vertex_scalar;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_perimeter;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_persistent_homology_approx;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_persistent_homology_diagram;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_point_cloud_registration;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_point_cloud_to_mesh_ball_pivot;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_point_containment;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_point_feature_histogram;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_point_normal_estimate;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_point_pair_distance;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_poisson_disk_sample;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_poisson_equation;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_position_arrays;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_position_stats;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_principal_directions;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_principal_stress_lines;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_project_to_xy;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_quad_remesh;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_quality_check;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_quality_histogram;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_random_color_faces;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_random_subdivide;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_random_subsample;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_random_walk_on_surface;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_reaction_diffusion;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_reeb_graph;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_reeb_graph_approx;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_region_label_smooth;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_remesh_adaptive;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_remove_degenerate;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_remove_duplicate_faces;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_remove_faces;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_remove_isolated;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_resample_points_on_surface;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_ring_select;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_saliency;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_sample_edges;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_sample_scalar_at_points;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_scalar_clamp;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_scalar_cluster_kmeans;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_scalar_combine;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_scalar_contour_bands;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_scalar_diffusion_anisotropic;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_scalar_field_critical;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_scalar_field_gradient_flow;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_scalar_field_laplacian;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_scalar_field_merge_tree;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_scalar_field_topology_ms;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_scalar_field_watershed;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_scalar_gradient;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_scalar_histogram;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_scalar_histogram_equalize;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_scalar_iso;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_scalar_isolate_region;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_scalar_math;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_scalar_normalize;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_scalar_percentile;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_scalar_range_color;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_scalar_ridge_valley;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_scalar_smooth;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_scalar_stats;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_scalar_threshold;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_scalar_threshold_extract;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_scalar_to_color;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_scalar_transfer;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_scalar_transfer_barycentric;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_scalar_watershed_merge;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_scale_per_vertex;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_scale_to_bounds;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_select_by_normal_direction;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_select_connected;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_self_intersection;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_shape_complexity;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_shape_context;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_shape_diameter_function;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_shape_distribution;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_shape_dna;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_shape_index;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_shape_index_full;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_shape_matching;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_sharp_edges;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_shortest_edge_path;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_shrink_faces;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_signed_distance_to_plane;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_simplify_quadric;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_skeleton;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_smooth_angle_weighted;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_smooth_bilateral;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_smooth_mean_curvature_flow;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_smooth_normal_filter;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_smooth_normals;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_smooth_scalar;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_smooth_subdivision_loop;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_sort_cells;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_spectral_clustering;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_spectral_mesh_processing;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_spectral_partition;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_spectral_shape_descriptor;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_sphere_map;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_spherical_coords;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_sphericity;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_spin_image;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_spin_surface;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_spin_transform;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_star_shaped;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_statistics;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_subdivide_butterfly_simple;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_subdivide_simple;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_surface_area_per_region;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_surface_integral;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_surface_integral_compute;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_surface_reconstruction_poisson;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_surface_sampling_blue_noise;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_surface_volume;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_symmetrize;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_symmetry;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_symmetry_measure;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_tangent_plane;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_texture_coord_normalize;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_texture_flatten;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_thicken_surface;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_thickness;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_to_point_cloud;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_topological_data_analysis;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_topological_morse_cancellation;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_topological_persistence;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_topological_simplification;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_topology_dual;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_topology_info;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_torus_parameterize;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_total_curvature;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_transform_util;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_tutte_embedding;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_twist_deform;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_uniform_sample;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_valence_stats;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_vector_field_on_surface;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_vertex_cluster;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_vertex_cluster_grid;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_vertex_cluster_octree;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_vertex_color_random;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_vertex_curvature_classify;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_vertex_degree_filter;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_vertex_edge_distance;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_vertex_feature_detect;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_vertex_index_array;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_vertex_laplacian_magnitude;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_vertex_normal_deviation;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_vertex_ring;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_vertex_ring_values;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_vertex_scatter_array;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_vertex_to_face;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_vertex_to_face_data;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_vertex_weld;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_visibility_from_point;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_volume_mesh_stats;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_voronoi_area;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_voronoi_on_surface;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_voronoi_partition;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_wave_equation;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_wave_kernel_signature;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_weighted_smooth;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_willmore_energy;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_wireframe;
pub mod midpoint_refine;
pub mod minimum_spanning_tree;
pub mod morph;
pub mod morphological_ops;
pub mod neighborhood_stats;
pub mod noise_displacement;
pub mod non_manifold_edges;
pub mod normal_consistency_check;
pub mod normals_from_faces;
pub mod obb;
pub mod offset;
pub mod offset_solid;
pub mod one_ring;
pub mod orient_faces;
pub mod paint;
pub mod paint_scalar;
pub mod parameterize;
pub mod parameterize_harmonic;
pub mod parameterize_tutte;
pub mod parametric_deform;
pub mod patch_extraction;
pub mod patch_select;
pub mod pca_axes;
pub mod pick;
pub mod planar_cut;
pub mod planar_section;
pub mod point_cloud_align;
pub mod point_cloud_from_mesh;
pub mod point_cloud_normal_estimation;
pub mod point_cloud_normals;
pub mod point_cloud_normals_orient;
pub mod point_cloud_outlier;
pub mod point_cloud_to_mesh;
pub mod point_cloud_to_vertices;
pub mod point_data_gradient;
pub mod point_data_interpolate;
pub mod point_data_range;
pub mod point_density;
pub mod point_in_mesh;
pub mod point_normals_recompute;
pub mod point_pair_features;
pub mod point_set_ops;
pub mod point_to_cell;
pub mod point_to_cell_data;
pub mod poisson_disk;
pub mod poisson_sample;
pub mod principal_axes;
pub mod principal_curvatures;
pub mod procrustes;
pub mod project_to_plane;
pub mod quad_remesh;
pub mod quality;
pub mod quality_histogram;
pub mod quality_report;
pub mod random_perturb;
pub mod random_sample_cells;
pub mod random_sample_points;
pub mod random_walk;
pub mod ray_cast;
pub mod ray_cast_mesh;
pub mod ray_query;
pub mod ray_triangle_intersect;
pub mod region_analysis;
pub mod region_grow;
pub mod remesh_isotropic;
pub mod remesh_quality;
pub mod remesh_uniform_simple;
pub mod remove_unused_points;
pub mod repair;
pub mod repair_advanced;
pub mod resample_on_grid;
pub mod ribbon_from_lines;
pub mod ring_buffer;
pub mod rotate;
pub mod saliency;
pub mod sample_surface;
pub mod sampling_stratified;
pub mod scalar_field_analysis;
pub mod scalar_field_topology;
pub mod scalar_gradient_on_mesh;
pub mod scalar_operations;
pub mod scalar_smoothing;
pub mod scale;
pub mod scale_space;
pub mod scatter_plot;
pub mod sdf_from_points;
pub mod segmentation;
pub mod select_by_normal;
pub mod select_by_region;
pub mod select_by_scalar_range;
pub mod select_cells_by_area;
pub mod self_intersection;
pub mod shape_descriptors;
pub mod shape_diameter;
pub mod sharp_edges;
pub mod signed_angle;
pub mod signed_angle_field;
pub mod signed_distance_field;
pub mod silhouette;
pub mod simplify_angle;
pub mod simplify_vertex_removal;
pub mod skeleton;
pub mod skeleton_extract;
pub mod skeleton_graph;
pub mod smooth_bilaplacian;
pub mod smooth_constrained;
pub mod smooth_cotangent;
pub mod smooth_hc;
pub mod smooth_laplacian_simple;
pub mod smooth_mesh_volume_preserving;
pub mod smooth_preserve_volume;
pub mod smooth_taubin;
pub mod smoothing_bilateral_normal;
pub mod smoothing_cotangent;
pub mod smoothing_pipeline;
pub mod spectral_descriptor;
pub mod sphere_clip;
pub mod spherical_harmonic_decompose;
pub mod spin;
pub mod spin_axis;
pub mod split_by_connectivity;
pub mod split_mesh;
pub mod spring_relaxation;
pub mod spring_system;
pub mod statistical_shape;
pub mod subdivide_edge;
pub mod subdivide_loop;
pub mod subdivide_quad;
pub mod subdivision_adaptive;
pub mod subdivision_sqrt3;
pub mod subdivision_ternary;
pub mod surface_area_by_region;
pub mod surface_area_compute;
pub mod surface_area_density;
pub mod surface_curvature_integral;
pub mod surface_integral;
pub mod surface_parameterization;
pub mod symmetry;
pub mod symmetry_detection;
pub mod symmetry_plane;
pub mod tangent_smooth;
pub mod taper;
pub mod tensor_field;
pub mod texture_atlas;
pub mod texture_transfer;
pub mod thicken;
pub mod thickness;
pub mod thinning;
pub mod topological_noise;
pub mod topology_analysis;
pub mod topology_check;
pub mod topology_distance;
pub mod topology_genus;
pub mod topology_info;
pub mod topology_repair;
pub mod topology_simplify;
pub mod transform_mesh;
pub mod transform_operations;
pub mod translate;
pub mod triangle_strip_convert;
pub mod triangulate_polygon;
pub mod triangulate_quads;
pub mod tube_from_lines;
pub mod twist;
pub mod unwrap;
pub mod unwrap_atlas;
pub mod uv_checker;
pub mod uv_from_projection;
pub mod uv_mapping;
pub mod uv_quality;
pub mod vertex_attribute_ops;
pub mod vertex_cluster;
pub mod vertex_cluster_by_normal;
pub mod vertex_cluster_kmeans;
pub mod vertex_clustering_spatial;
pub mod vertex_color_blend;
pub mod vertex_color_from_position;
pub mod vertex_color_from_scalar;
pub mod vertex_color_transfer;
pub mod vertex_coloring;
pub mod vertex_curvature_gaussian;
pub mod vertex_displacement;
pub mod vertex_displacement_array;
pub mod vertex_importance;
pub mod vertex_merge_by_distance;
pub mod vertex_neighbors;
pub mod vertex_normal_deviation;
pub mod vertex_normal_estimation;
pub mod vertex_normal_smooth;
pub mod vertex_normal_weight;
pub mod vertex_ring_ops;
pub mod vertex_scatter;
pub mod vertex_split;
pub mod vertex_star;
pub mod vertex_to_cell;
pub mod vertex_to_polydata;
pub mod vertex_valence_compute;
pub mod visibility;
pub mod visibility_analysis;
pub mod volume;
pub mod volume_compute;
pub mod voronoi_cell_area;
pub mod voronoi_cells;
pub mod voronoi_diagram_2d;
pub mod voxelize;
pub mod warp_by_scalar;
pub mod warp_by_vector;
pub mod watertight_check;
pub mod wave_deform;
pub mod wave_propagation;
pub mod wave_simulation;
pub mod weighted_smooth;
pub mod weld_vertices;
pub mod wire_ops;
pub mod wireframe_extract;
pub mod static_clean;
pub mod boolean_operations;
pub mod youngs_interface;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_cylindrical_coords;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_radial_distance;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_scalar_diffuse;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_scalar_gradient_magnitude;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_scalar_invert;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_scalar_laplacian;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_scalar_quantize;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_scalar_remap;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_vertex_angle_sum;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_vertex_distance_to_point;
#[cfg(feature = "filters-mesh-extra")]
pub mod mesh_vertex_gaussian;
