// Always available
pub mod core;
pub mod geometry;
pub mod extract;
pub mod normals;
pub mod clip;
pub mod points;

// Feature-gated filter groups
#[cfg(feature = "filters-image")]
pub mod image;
#[cfg(feature = "filters-mesh")]
pub mod mesh;
#[cfg(feature = "filters-smooth")]
pub mod smooth;
#[cfg(feature = "filters-transform")]
pub mod transform;
#[cfg(feature = "filters-subdivide")]
pub mod subdivide;
#[cfg(feature = "filters-cell")]
pub mod cell;
#[cfg(feature = "filters-statistics")]
pub mod statistics;
#[cfg(feature = "filters-texture")]
pub mod texture;
#[cfg(feature = "filters-flow")]
pub mod flow;
#[cfg(feature = "filters-boolean")]
pub mod boolean;
#[cfg(feature = "filters-grid")]
pub mod grid;
#[cfg(feature = "filters-data")]
pub mod filter_data;
#[cfg(feature = "filters-distance")]
pub mod distance;
#[cfg(feature = "filters-gpu")]
pub mod gpu;
